inputHorm1DiffCoeff = [[inputHorm1DiffCoeff]]
horm1Efficacy = [[horm1Efficacy]]
horm1DivOrientVertComp = [[horm1DivOrientVertComp]]
horm1DivOrientHoriComp = [[horm1DivOrientHoriComp]]

horm1toHorm2Ratio = [[horm1toHorm2Ratio]]
horm2Efficacy = [[horm2Efficacy]]
hormone2IntroTime = [[hormone2IntroTime]]
horm2SourceHor = [[horm2SourceHor]]
horm2SourceVer = [[horm2SourceVer]]
horm2DivOrientVertComp = [[horm2DivOrientVertComp]]
horm2DivOrientHoriComp = [[horm2DivOrientHoriComp]]

RDfeedRate = [[RDfeedRate]]
RDfeedToKillRatio= [[RDfeedToKillRatio]]
reactRate1to2 = [[reactRate1to2]]
lengthOfHorm2Prod = [[lengthOfHorm2Prod]]
